// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: const String.fromEnvironment(
      'FIREBASE_API_KEY',
      defaultValue: 'AIzaSyBMEsuXF9BQJoyf24UZkbXKxKPggjQCyEI', // Development fallback
    ),
    appId: '1:629608785619:web:PLACEHOLDER',
    messagingSenderId: '629608785619',
    projectId: 'friendsride-v2',
    authDomain: 'friendsride-v2.firebaseapp.com',
    storageBucket: 'friendsride-v2.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: const String.fromEnvironment(
      'FIREBASE_API_KEY',
      defaultValue: 'AIzaSyBMEsuXF9BQJoyf24UZkbXKxKPggjQCyEI', // Development fallback
    ),
    appId: '1:629608785619:android:b2a481ff7cdaae65359626',
    messagingSenderId: '629608785619',
    projectId: 'friendsride-v2',
    storageBucket: 'friendsride-v2.firebasestorage.app',
  );
}